apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: longhorn
spec:
  helm:
    version: v1.7.2
    releaseName: longhorn
    repo: https://charts.longhorn.io
    chart: longhorn
    values:
      defaultSettings:
        defaultReplicaCount: 2
  namespace: longhorn-system
  targets:
  - clusterSelector:
    matchLabels:
      management.cattle.io/cluster-display-name: my-longhorn-cluster
