apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: longhorn
spec:
  helm:
    version: v1.7.2
    releaseName: longhorn
    repo: https://charts.longhorn.io
    chart: longhorn
    values:
      defaultSettings:
        defaultReplicaCount: 2
  namespace: longhorn-system
  targets:
  - clusterSelector:
      matchExpressions:
      - key: clusterclass-name.fleet.addons.cluster.x-k8s.io
        operator: In
        values:
          - my-longhorn-cluster
